name: Lider Sale CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs:
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle Test
      run: ./gradlew clean check jacocoTestReport
