name: Lider Sale CI

on:
  push:
    branches: [ stage ]
  pull_request:
    branches: [ stage ]

jobs:
  test:
    name: Test - Units & Integrations
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 11.0.4
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Gradle Test
      run: ./gradlew clean check jacocoTestReport

  sonar:
    name: Test - SonarCloud Scan
    runs-on: ubuntu-18.04
    needs: [test]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11.0.4
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Generate jacoco report
        run: ./gradlew clean check jacocoTestReport
      - name: SonarCloud Scan
        run: ./gradlew -Dsonar.login=${{ secrets.SONAR_TOKEN }} sonarqube  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}